"""CRUD API for maintenance windows — alert suppression during planned outages.

T9 Tur 6A adds cyclic (recurring) windows. A template row has recurrence
set; the spawn beat task materializes child instance rows (parent_window_id
points back) with recurrence=NULL — the existing suppression check stays
unchanged.
"""
from datetime import datetime, timezone
from typing import Any, Optional

from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.database import get_db
from app.core.deps import CurrentUser
from app.models.maintenance_window import MaintenanceWindow

router = APIRouter()


def _serialize(w: MaintenanceWindow) -> dict[str, Any]:
    return {
        "id": w.id,
        "name": w.name,
        "description": w.description,
        "start_time": w.start_time.isoformat(),
        "end_time": w.end_time.isoformat(),
        "applies_to_all": w.applies_to_all,
        "device_ids": w.device_ids or [],
        "created_by": w.created_by,
        "created_at": w.created_at.isoformat(),
        "is_active": w.start_time <= datetime.now(timezone.utc) <= w.end_time,
        # T9 Tur 6A — cyclic fields
        "recurrence": w.recurrence,
        "recur_days_of_week": w.recur_days_of_week or [],
        "recur_day_of_month": w.recur_day_of_month,
        "recur_count_max": w.recur_count_max,
        "recur_until": w.recur_until.isoformat() if w.recur_until else None,
        "recur_instances_spawned": w.recur_instances_spawned,
        "parent_window_id": w.parent_window_id,
        "is_recurrence_template": w.recurrence is not None and w.parent_window_id is None,
    }


@router.get("")
async def list_windows(
    db: AsyncSession = Depends(get_db),
    include_instances: bool = False,
):
    """Templates + instances by default. Set include_instances=false to
    only return templates and one-shot windows (hides the autogenerated
    child rows from the list view)."""
    q = select(MaintenanceWindow).order_by(MaintenanceWindow.start_time.desc())
    if not include_instances:
        q = q.where(MaintenanceWindow.parent_window_id.is_(None))
    result = await db.execute(q)
    return [_serialize(w) for w in result.scalars().all()]


@router.get("/active")
async def list_active_windows(db: AsyncSession = Depends(get_db)):
    """Returns windows that are currently active (now is between start and end)."""
    now = datetime.now(timezone.utc)
    result = await db.execute(
        select(MaintenanceWindow).where(
            MaintenanceWindow.start_time <= now,
            MaintenanceWindow.end_time >= now,
        )
    )
    return [_serialize(w) for w in result.scalars().all()]


@router.get("/{window_id}/upcoming")
async def list_upcoming_instances(
    window_id: int,
    limit: int = 20,
    db: AsyncSession = Depends(get_db),
):
    """For a recurrence template, return its already-materialized child
    instances (closest in the future first). Returns the children that the
    beat task has spawned — call again later to see more."""
    parent = (await db.execute(
        select(MaintenanceWindow).where(MaintenanceWindow.id == window_id)
    )).scalar_one_or_none()
    if parent is None:
        raise HTTPException(status_code=404, detail="Not found")
    if parent.recurrence is None:
        return []
    rows = (await db.execute(
        select(MaintenanceWindow)
        .where(MaintenanceWindow.parent_window_id == window_id)
        .order_by(MaintenanceWindow.start_time.asc())
        .limit(limit)
    )).scalars().all()
    return [_serialize(r) for r in rows]


@router.post("", status_code=status.HTTP_201_CREATED)
async def create_window(
    payload: dict,
    current_user: CurrentUser = None,
    db: AsyncSession = Depends(get_db),
):
    _validate(payload)
    recurrence, recur_fields = _extract_recurrence(payload)
    w = MaintenanceWindow(
        name=payload["name"],
        description=payload.get("description"),
        start_time=datetime.fromisoformat(payload["start_time"]),
        end_time=datetime.fromisoformat(payload["end_time"]),
        applies_to_all=bool(payload.get("applies_to_all", False)),
        device_ids=payload.get("device_ids") or [],
        created_by=current_user.id,
        recurrence=recurrence,
        **recur_fields,
    )
    db.add(w)
    await db.commit()
    await db.refresh(w)
    return _serialize(w)


@router.patch("/{window_id}")
async def update_window(
    window_id: int,
    payload: dict,
    current_user: CurrentUser = None,
    db: AsyncSession = Depends(get_db),
):
    result = await db.execute(select(MaintenanceWindow).where(MaintenanceWindow.id == window_id))
    w = result.scalar_one_or_none()
    if not w:
        raise HTTPException(status_code=404, detail="Not found")

    if "name" in payload:
        w.name = payload["name"]
    if "description" in payload:
        w.description = payload["description"]
    if "start_time" in payload:
        w.start_time = datetime.fromisoformat(payload["start_time"])
    if "end_time" in payload:
        w.end_time = datetime.fromisoformat(payload["end_time"])
    if "applies_to_all" in payload:
        w.applies_to_all = bool(payload["applies_to_all"])
    if "device_ids" in payload:
        w.device_ids = payload["device_ids"] or []
    # Recurrence updates only valid on templates (a spawned child cannot
    # become a template by mutation — would corrupt the parent_window_id link).
    if any(k in payload for k in ("recurrence", "recur_days_of_week",
                                  "recur_day_of_month", "recur_count_max",
                                  "recur_until")):
        if w.parent_window_id is not None:
            raise HTTPException(
                status_code=400,
                detail="Cyclic alanlar yalnız template satırlarda değiştirilebilir (child instance üzerinde değil).",
            )
        recurrence, recur_fields = _extract_recurrence(payload)
        # Allow clearing by sending recurrence=null explicitly
        if "recurrence" in payload:
            w.recurrence = recurrence
        for k, v in recur_fields.items():
            setattr(w, k, v)

    await db.commit()
    await db.refresh(w)
    return _serialize(w)


@router.delete("/{window_id}", status_code=status.HTTP_204_NO_CONTENT)
async def delete_window(
    window_id: int,
    current_user: CurrentUser = None,
    db: AsyncSession = Depends(get_db),
):
    result = await db.execute(select(MaintenanceWindow).where(MaintenanceWindow.id == window_id))
    w = result.scalar_one_or_none()
    if not w:
        raise HTTPException(status_code=404, detail="Not found")
    # Deleting a template ON DELETE CASCADE'es the child instances too.
    await db.delete(w)
    await db.commit()


def _validate(payload: dict):
    if not payload.get("name"):
        raise HTTPException(status_code=422, detail="name is required")
    if not payload.get("start_time") or not payload.get("end_time"):
        raise HTTPException(status_code=422, detail="start_time and end_time are required")
    try:
        st = datetime.fromisoformat(payload["start_time"])
        et = datetime.fromisoformat(payload["end_time"])
    except (ValueError, TypeError):
        raise HTTPException(status_code=422, detail="Invalid datetime format (use ISO 8601)")
    if et <= st:
        raise HTTPException(status_code=422, detail="end_time must be after start_time")
    rec = payload.get("recurrence")
    if rec is not None and rec not in ("daily", "weekly", "monthly"):
        raise HTTPException(status_code=422, detail="recurrence must be daily/weekly/monthly")
    if rec == "weekly":
        dow = payload.get("recur_days_of_week") or []
        if not isinstance(dow, list) or not dow or not all(isinstance(d, int) and 0 <= d <= 6 for d in dow):
            raise HTTPException(status_code=422, detail="recur_days_of_week (0..6, Mon=0) gerekli")
    if rec == "monthly":
        dom = payload.get("recur_day_of_month")
        if not isinstance(dom, int) or not 1 <= dom <= 28:
            raise HTTPException(status_code=422, detail="recur_day_of_month (1..28) gerekli")


def _extract_recurrence(payload: dict) -> tuple[Optional[str], dict]:
    """Pull recurrence fields out of an upsert payload."""
    recurrence = payload.get("recurrence")
    recur_until = payload.get("recur_until")
    fields: dict[str, Any] = {
        "recur_days_of_week": payload.get("recur_days_of_week") if recurrence == "weekly" else None,
        "recur_day_of_month": payload.get("recur_day_of_month") if recurrence == "monthly" else None,
        "recur_count_max": payload.get("recur_count_max"),
        "recur_until": datetime.fromisoformat(recur_until) if recur_until else None,
    }
    return recurrence, fields
